version: '3.5'

services:

  local-postsales-db:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: "uber-clone-db"
      POSTGRES_USER: "uber_clone_user"
      POSTGRES_PASSWORD: "uber_clone_password"
    ports:
      - 5442:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data2
    container_name: local-uber-clone-db
    networks:
      - uber-clone-shared-net

  integ-test-db:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: "uber-clone-db-integtest"
      POSTGRES_USER: "uber_clone_user"
      POSTGRES_PASSWORD: "uber_clone_password"
    ports:
      - 5443:5432
    container_name: local-integ-test-uber-clone-postgres
    networks:
      - uber-clone-shared-net

volumes:
  postgres-data:
    external: false

networks:
  uber-clone-shared-net:
    name: uber-clone-shared-net
