server.port: 7777
server.shutdown: immediate

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5443/uber-clone-db-integtest
      username: uber_clone_user
      password: uber_clone_password
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true