spring:
  profiles:
    active: dev
  application:
    name: uber-clone-service
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      data-source-properties:
        string type: unspecified
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 30s